chatapp/myapp/chat/urls.py
from django.conf.urls import url
from . import views
app_name='chat'
urlpatterns = [
    url(r'^$', views.index, name='index'),  # 127.0.0.0:8000/
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login,name='user_login'),
    url(r'^room/(?P<room_name>[^/]+)/$', views.room, name='room'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate')
]

chatapp/myapp/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from chat import views
urlpatterns = [

    url('', include('chat.urls')),
    url(r'^special/', views.special, name='special'),
    url(r'^chat/',include('chat.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    #
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    #
    url(r'^enter/', views.enter, name='enter')


]

chatapp/myapp/chat/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

chatapp/myapp/chat/forms.py
from django import forms

from django.contrib.auth.models import User



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta():
        model = User
        fields = ('username', 'password', 'email')

chatapp/myapp/chat/views.py
from django.shortcuts import render
import json
from django.utils.safestring import mark_safe
from django.shortcuts import render
from chat.forms import UserForm
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.models import User
from .tokens import account_activation_token


# this method is used to display the home page
def index(request):
    return render(request, 'chat/indexs.html', {})


@login_required     # only after login of user this method can be called
def enter(request):     # this method is used to enter the chat lobby
        return render(request, 'chat/index.html', {})


def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })


@login_required     # only  after login of user this method can be called
def special(request):
    return HttpResponse("You are logged in !")


@login_required    # only after login of user this method can be called
def user_logout(request):       # this method is used to logout
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):      # this method is used to signup the user
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('chat/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                # takes user id and generates the base64 code(uidb64)
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                # Here we receive uidb64, token. By using the "urlsafe_base64_decode"
                # we decode the base64 encoded uidb64 user id.
                # We query the database with user id to get user
                'token': account_activation_token.make_token(user),
                # takes the user object and generates the onetime usable token for the user(token)
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')

    else:
        user_form = UserForm()

    return render(request, 'chat/registration.html',
                           {'user_form': user_form})


def user_login(request):        # this method is used to login the user
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        # authentication of user name and password
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return render(request, 'chat/index.html', {})
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'chat/login.html', {})


def activate(request, uidb64, token):   # this method is used to generate confirmation mail to the user
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))  # uid: The user’s primary key encoded in base 64.
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        # We check the token validation
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

chatapp/myapp/chat/templates/chat/acc_active_email.html
 {% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'chat:activate' uidb64=uid token=token %}
{% endautoescape %}

chatapp/myapp/chat/templates/chat/base.html
<!DOCTYPE html>
<html>

  <head>

    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}

          <li><a class="navbar-brand" href="{% url 'index' %}">CHATAPP</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'chat:register' %}">Register</a></li>


          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'enter' %}">Enter Chat Room</a> </li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'chat:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>

</html>

chatapp/myapp/chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body bgcolor="#E1FAE4">
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = roomName + '/';
        };
    </script>
</body>
</html>

chatapp/myapp/chat/templates/chat/indexs.html
{% extends "chat/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Chatapp!!! </h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

chatapp/myapp/chat/templates/chat/login.html
{% block body_block %}
<body BGCOLOR="#F5D69E">
  <div class="container">
    <div class="jumbotron">
      <h1><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-sluu5q5UljhHkiExP_b867CkpAOhoKa3sKIXjg4rE10rTS5w" width="1280" height="100">
      </h1>
<form method="post" action="{% url 'chat:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
      
  </div>
</body>
{% endblock %}

chatapp/myapp/chat/templates/chat/registration.html
{% load staticfiles %}
{% block body_block %}

<body bgcolor="#C3D4F8">

  <div class="container">
    <div class="jumbotron">
        
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1><img src="http://www.letslovelife.co.uk/wp-content/uploads/2015/04/Sign-Up-Header.png"width="600" height="100"></h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

    </div>

      {% endif %}

  </div>

</body>
{% endblock %}

chatapp/myapp/chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body bgcolor="#F7D3C7">
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };

</script>

</html>